### ISSUE TITLE
mgm matlab

### ISSUE THREAD

**Issue by Kimeu-Jeff** [gfacciol/mgm#11]
Hi gfacciol
Thanks for providing your code. I am trying to implement the Matlab implementation and am getting error in MGM_wrapper.
>> runme
./mgm_o: /usr/local/MATLAB/R2016b/sys/os/glnxa64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./mgm_o)
Error using MGM_wrapper (line 104)
Cannot open file output.bin

Error in stereomatch_MGM (line 66)
   dmap = MGM_wrapper(pcost, NDIR, P1, P2, MGM, VTYPE, w);

Error in runme (line 14)
   [dmap,t] = stereomatch_MGM(L, R, dmax, DIR, P1, P2, MGM);

How is this output.bin created? Thank you

**Comment by gfacciol** [comment]
I think that the file output.bin was not created because the call to mgm_o  failed. You should recompile it.
