### ISSUE TITLE
What's the major difference between mgm and mgm_multi?

### ISSUE THREAD

**Issue by drzhouq** [gfacciol/mgm#12]
absolute newbie on this subject and could not find any documentation on this topic. Can you shed some lights on this?

**Comment by gfacciol** [comment]
mgm implements the BMVC paper. 
mgm_multi implements a coarse-to-fine multiscale strategy similar to the one described in 
>             Reliable multiscale and multiwindow stereo matching
>             A Buades, G Facciolo - SIAM Journal on Imaging Sciences, 2015
>             http://dev.ipol.im/~facciolo/pub/SIIMS2014rev.pdf

Some notes about it's use can be found in:
https://github.com/gfacciol/mgm/blob/multiscale/README_multiscale.md

**Comment by drzhouq** [comment]
many thanks @gfacciol for your response. two following up questions: 1)is mgm_multi the preferred algo among all the options? 2) if one has a large image, will the result be better to process the entire image in one go (full_image) or slice the image into a few AOIs?  full_image requires way much more memory.

**Comment by gfacciol** [comment]
1. Yes, mgm_multi usually yields better results faster.
2. It depends on what you call a large image. 4000x3000, will require a lot of memory but it will work. 
However, large (40000x40000) satellite images for instance, will not fit in memory and other unforeseen scale issues might come up. That's one of the reasons for developing [s2p](https://github.com/cmla/s2p)

Slicing/Tiling the image with a reasonable overlap will produce almost identical results to the final image, and each sub-image can run on parallel threads.

**Comment by drzhouq** [comment]
@gfacciol Super. Thanks a million.
