### ISSUE TITLE
mgm fails with SIGABRT (6)

### ISSUE THREAD

**Issue by drzhouq** [gfacciol/mgm#13]
when running mgm, we got random sigabbt error. core dumps are also been generated when error take place
<img width="1340" alt="Screen Shot 2020-12-29 at 11 14 50 AM" src="https://user-images.githubusercontent.com/3936288/103309670-8c3d9680-49ca-11eb-8de4-83ffe5c9a6bc.png">

**Comment by gfacciol** [comment]
This is an issue with s2p, who's calling mgm. 
Abort is sent to mgm probably because of a timeout.

**Comment by drzhouq** [comment]
@gfacciol our mgm_timeout was set to 24 hours, which obscenely long. We were running s2p process on a 96 vcpus / 512G AWS EC2. But the issue is moot since the preferred algo is mgm_multi, we will try to get that work. It seems to us that mgm produces better results than mgm_multi, for some unknown reason

**Comment by gfacciol** [comment]
Thanks for the feedback! I'd greatly appreciate if you have an example, that you can share, showing the difference between mgm and mgm_multi. It would help in finding explaination.
