### ISSUE TITLE
Results instability with mgm and mgm_multi @ac54122

### ISSUE THREAD

**Issue by mcournet** [gfacciol/mgm#2]
Hello Gabriele,

It seems that two consecutive executions of [mgm @ac54122](https://github.com/gfacciol/mgm/commits/ac541222e207ee2324fbb789f47677b1e874ab8b) are not producing the same results.
It is the same for [mgm_multi @ac54122](https://github.com/gfacciol/mgm/commits/ac541222e207ee2324fbb789f47677b1e874ab8b).

You can refer to the example given in the mgm_multi_ac54122.tar.gz attached. On this example, on two consecutive executions of [mgm @ac54122](https://github.com/gfacciol/mgm/commits/ac541222e207ee2324fbb789f47677b1e874ab8b), the following statistics were obtained on these two outputs difference : min=-0.33827555, max=0.72447157, mean=5.896214e-06, std=0.0023109724 (stats obtained on "rectified_disp1.tif - rectified_disp2.tif" also included in the tar.gz). 

[mgm @ac54122](https://github.com/gfacciol/mgm/commits/ac541222e207ee2324fbb789f47677b1e874ab8b) and [mgm_multi @ac54122](https://github.com/gfacciol/mgm/commits/ac541222e207ee2324fbb789f47677b1e874ab8b) are the mgm and mgm_multi default versions of [s2p](https://github.com/MISS3D/s2p/commit/ddece81b5770245c793cede07f1b96d813ae2d40#diff-cd5dbf3629c558b0104ba8f0937d6816) since 29 Oct 2018, as agreed.

Could you please give me a feedback on this topic ?

Thanks,
Myriam
[mgm_multi_ac54122.tar.gz](https://github.com/gfacciol/mgm/files/2844737/mgm_multi_ac54122.tar.gz)

**Comment by gfacciol** [comment]
This is due to parallelism. A register is being updated without verifying concurrence here:
https://github.com/gfacciol/mgm/blob/a5322ab74ea391658da1ae8d5f51d4c6b4847ae1/dvec.cc#L114
If you call mgm with OMP_NUM_THREADS=1 the issue goes away.
Otherwise uncommenting the line above will reduce the difference to numerical precision. 
However, the result will never be exact due to non commutativity of floating point additions.

**Comment by gfacciol** [comment]
Just updated the code by removing the comment in: https://github.com/gfacciol/mgm/commit/468b4909dbd1cd9be96f2329e351927306acce73

**Comment by mcournet** [comment]
Gabriele, thank you very much for your feedback and for the code update.
Could you please replace the [S2P](https://github.com/MISS3D/s2p/tree/master/3rdparty) default version of mgm_multi by https://github.com/gfacciol/mgm/commit/468b4909dbd1cd9be96f2329e351927306acce73 ?

**Comment by gfacciol** [comment]
done!
