### ISSUE TITLE
Would it be possible to ctypes the use of cost volume MGM optimization ?

### ISSUE THREAD

**Issue by dumasl** [gfacciol/mgm#3]
This is not really an issue, more like a question or a request.

I was personally wondering if somehow it could be possible / make sense, to allow someone to use MGM only for the cost volume optimization part  ?
Say for example that I have a stereo algorithm that can perform steps 1 & 2 as defined by Scharstein & Szeliski taxonomy leaving me with a Cost Volume in memory ready to be optimized by a global matching algorithm like MGM for instance. Then it would be of great use to be able to plug your MGM optimization by giving my cost volume as input to your software.

I'm aware of the ctypes branch of MGM but unless I am mistaken I believe it aims at allowing someone to give both input images to MGM as numpy arrays ? Not to allow someone to give MGM a cost volume as numpy array right ? 

Obviously I am not saying MGM should provide such a functionality, just wondering what you would think of it and how it could fit the roadmap you might have for MGM in the near future.

Thank you for the time you'll spend on this issue.

**Comment by gfacciol** [comment]
The functionality of processing a user provided costvolume is already implemented in mgm with the flag -inputCostVolume.
