### ISSUE TITLE
Unable to replicate paper results

### ISSUE THREAD

**Issue by methylDragon** [gfacciol/mgm#7]
I've been trying to generate similar results from the paper, but have been unable to.

Running the example calls results in bad disparity images, and I'm not sure how to tune the parameters to fix them and have a disparity image that approximates the ground truth one, or the ones generated by the online demo.

I'm not sure what the issue is though, any help would be really appreciated!

### Fountain (example 2.1 and 2.2)
Cost:
![cost](https://user-images.githubusercontent.com/20265670/61791707-4da6c280-ae4d-11e9-9245-cdb8a5f54b16.png)

Disparity:
![disp](https://user-images.githubusercontent.com/20265670/61791712-51d2e000-ae4d-11e9-9e03-2e218e4d8172.png)

### Satellite (example 2.3)
Cost:
![cost](https://user-images.githubusercontent.com/20265670/61791647-2e0f9a00-ae4d-11e9-9002-18d98c8fb639.png)

Disparity:
![disp](https://user-images.githubusercontent.com/20265670/61791643-2b14a980-ae4d-11e9-810f-11a532a24d4c.png)

**Comment by gfacciol** [comment]
Dear @methylDragon, 
Its seems that you are trying to visualize the output images with a viewer that doesn't support floating point TIFFs. Indeed the disparities in your outputs are in the range [-30, 60]. 
You can use different programs to read and view the output images:  
![image](https://user-images.githubusercontent.com/5002346/61792522-3cde5880-ae1d-11e9-9886-58aadfbfe9b5.png)

* https://github.com/gfacciol/pvflip   ;  a personal favorite ;) 
* [imageJ](https://imagej.nih.gov/ij/) 
* even python (after installing the iio package) 

best, 
gabriele
